### ISSUE TITLE
Increase of memory usage

### ISSUE THREAD

**Issue by shotaizu** [seunghophysics/NTag#42]
When I processed AddNoise with ``in_noise`` option, I observed linear increase of memory usage. I attached the massif profile, which shows the component ``std::_Vector_base<int,...>``is increasing. This indicates the large TQLIST or TQALIST branches affect this increase.
Once after it exceed the limit of the computing system (4GB), it is killed. Therefore, it might be better to have countermeasures, I thik.

Note: I think this promlem is ciritical only when noise files are loaded via this ``in_noise`` option with a RegEx form because the part to load noise files via ``noise_path`` will check number of loaded files not to load too much.

## Command
```
/home/sizu/sk6/sle_threshold.20230906.d/NTag/bin/AddNoise -in /disk03/usr8/sizu/sk6/sle_threshold.20230906.data.d/mc/out/nicfmc_086744_35.3_-70.7_0_100000ev.root -out /disk03/usr8/sizu/sk6/sle_threshold.20230906.data.d/mc/out/nicfmc_086744_35.3_-70.7_0_100000ev.mccomb.root -TNOISESTART -5 -TNOISEEND 535 -SKGEOMETRY 6 -in_noise /disk02/calib3/realtime/rndm/086744/*.root -NOISESEED 86844
```

[massif.out.3308882.txt](https://github.com/seunghophysics/NTag/files/12679885/massif.out.3308882.txt)

**Comment by seunghophysics** [comment]
Resolved by #43
